// Generated by CoffeeScript 1.9.3
(function() {
  (function() {
    $('.articleContent ul.tabs').on('click', 'li', function(e) {
      var activeIndex;
      if ($(this).hasClass('active')) {
        return;
      }
      $(this).addClass("active");
      $(this).siblings().removeClass("active");
      activeIndex = $(this).closest('ul').find('li').index(this);
      $('ul.articles').eq(activeIndex).removeClass("hide");
      return $('ul.articles').eq(activeIndex).siblings("ul.articles").addClass("hide");
    });
    $('.mostArticle ul.tabs').on('click', 'li', function(e) {
      var activeIndex;
      if ($(this).hasClass('active')) {
        return;
      }
      $(this).addClass("active");
      $(this).siblings().removeClass("active");
      activeIndex = $(this).closest('ul').find('li').index(this);
      $('ul.most').eq(activeIndex).removeClass("hide");
      return $('ul.most').eq(activeIndex).siblings("ul.most").addClass("hide");
    });
    return $('.slideControl').on('click', 'li', function(e) {
      var activeIndex;
      if ($(this).hasClass('active')) {
        return;
      }
      $(this).addClass("active");
      $(this).siblings().removeClass("active");
      activeIndex = $(this).closest('ul').find('li').index(this);
      $('li.singleImage').eq(activeIndex).removeClass("hide");
      $('li.singleImage').eq(activeIndex).siblings("li").addClass("hide");
      $('li.singleStory').eq(activeIndex).removeClass("hide");
      return $('li.singleStory').eq(activeIndex).siblings("li").addClass("hide");
    });
  })();

  

}).call(this);
